### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by lubby24** [veralauee/DPatch#6]
When I run demo.py or train.py or test.py ,and I am getting this error:

initial model without patch
load model succ...
Traceback (most recent call last):
  File "demo.py", line 65, in <module>
    bbox_pred, iou_pred, prob_pred = net(im_data, attack=args.attack)
  File "/home/lubby/anaconda3/envs/dpatch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/lubby/4Tdisk/DPatch/darknet.py", line 208, in forward
    conv1s = self.conv1s(im_data)
  File "/home/lubby/anaconda3/envs/dpatch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lubby/anaconda3/envs/dpatch/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/lubby/anaconda3/envs/dpatch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lubby/anaconda3/envs/dpatch/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/lubby/anaconda3/envs/dpatch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/lubby/4Tdisk/DPatch/utils/network.py", line 35, in forward
    x = self.conv(x)
  File "/home/lubby/anaconda3/envs/dpatch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lubby/anaconda3/envs/dpatch/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

I want to know your CUDA version.
does anyone know, what is causing this?

My environment:
systerm ubuntu 18.04
gpu: NVIDIA RTX TITAN
python : 3.6.0
cuda: 9.0
cudnn:7.5.1

**Comment by jieweilai** [comment]
hello，i meet a problem as follow：
when i want to debug train.py and test.py,there is a error:
    from ._reorg_layers import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'layers.reorg._ext.reorg_layer._reorg_layers'
Have you encountered such a problem, can you tell me how to solve it?

**Comment by tangchuanming1995** [comment]
> hello，i meet a problem as follow：
> when i want to debug train.py and test.py,there is a error:
> from ._reorg_layers import lib as _lib, ffi as _ffi
> ModuleNotFoundError: No module named 'layers.reorg._ext.reorg_layer._reorg_layers'
> Have you encountered such a problem, can you tell me how to solve it?

hello,me too. i just run demo.py  ,and the Error is same with u

**Comment by Tchuanm** [comment]
> hello，i meet a problem as follow：
> when i want to debug train.py and test.py,there is a error:
> from ._reorg_layers import lib as _lib, ffi as _ffi
> ModuleNotFoundError: No module named 'layers.reorg._ext.reorg_layer._reorg_layers'
> Have you encountered such a problem, can you tell me how to solve it?

hello,me too. i just run demo.py ,and the Error is same with u
did u solve it ?

**Comment by jieweilai** [comment]
i think you should install the cuda-9.0 and torch-0.4.0.However,i should tell that this work is extremely painful



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangchuanming1995"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 晚上7:23
收件人: "veralauee/DPatch"<DPatch@noreply.github.com&gt;; 
抄送: "『☆初陽卍綻放』"<2556004343@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [veralauee/DPatch] RuntimeError: CUDNN_STATUS_EXECUTION_FAILED (#6)





  
hello，i meet a problem as follow：
 when i want to debug train.py and test.py,there is a error:
 from ._reorg_layers import lib as _lib, ffi as _ffi
 ModuleNotFoundError: No module named 'layers.reorg._ext.reorg_layer._reorg_layers'
 Have you encountered such a problem, can you tell me how to solve it?
  
hello,me too. i just run demo.py ,and the Error is same with u
 did u solve it ?

**Comment by Tchuanm** [comment]
> i think you should install the cuda-9.0 and torch-0.4.0.However,i should tell that this work is extremely painful
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tangchuanming1995"<notifications@github.com&gt;; 发送时间: 2020年8月20日(星期四) 晚上7:23 收件人: "veralauee/DPatch"<DPatch@noreply.github.com&gt;; 抄送: "『☆初陽卍綻放』"<2556004343@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [veralauee/DPatch] RuntimeError: CUDNN_STATUS_EXECUTION_FAILED (#6) hello，i meet a problem as follow： when i want to debug train.py and test.py,there is a error: from ._reorg_layers import lib as _lib, ffi as _ffi ModuleNotFoundError: No module named 'layers.reorg._ext.reorg_layer._reorg_layers' Have you encountered such a problem, can you tell me how to solve it? hello,me too. i just run demo.py ,and the Error is same with u did u solve it ? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

thanks, and torch & cuda is right.but it still not work. painful～

**Comment by yebin999** [comment]
> > hello，i meet a problem as follow：
> > when i want to debug train.py and test.py,there is a error:
> > from ._reorg_layers import lib as _lib, ffi as _ffi
> > ModuleNotFoundError: No module named 'layers.reorg._ext.reorg_layer._reorg_layers'
> > Have you encountered such a problem, can you tell me how to solve it?
> 
> hello,me too. i just run demo.py ,and the Error is same with u
> did u solve it ?

hello,you can do the step following the make.sh, then the problem will go

**Comment by ruixin-han** [comment]
The cause of this problem may be a mismatch between the CUDA version and pytorch

**Comment by alexlorenzo** [comment]
Hello,
To avoid this problem I downloaded cuda9.1 using this link [Cuda 9.1 on Ubuntu 18.04](https://gist.github.com/DaneGardner/accd6fd330348543167719002a661bd5).

Then don't forget to install all recommended packages + `conda install pytorch=0.4.1 cuda91 -c pytorch`.

Hope my comment will help others.
